import express from "express"
import axios from "axios"

export const routes = express.Router()
export const index = "/"

const styles = [4, 83, 107, 77, 116, 115, 114, 69, 113, 104, 97, 105, 94, 111, 105]

routes.get("/", (req, res) => {
  res.render('index')
})

routes.post("/generate-img", async (req, res) => {
  const data = await send_task_to_dream_api(styles[Math.floor(styles.length * Math.random())], req.body.prompt, req.body.weight).catch(() => console.log("error"))
  res.send(data)
})

async function send_task_to_dream_api(style_id, prompt, weight) {
  const BASE_URL = 'https://api.luan.tools/api/tasks/';
  // Step 0: Auth
  // Set your authorization key to the key generated by your Dream API Dashboard
  const headers = {
    headers: {
      Authorization: `Bearer QSael7AY7SNV9IQ4QniHkLIxHkL4uMog`,
      'Content-Type': 'application/json'
    }
  }

  // Step 1) make a POST request to https://api.luan.tools/api/tasks/
  let post_payload = { "use_target_image": false };

  console.log("Creating task...")
  let response = await axios.post(BASE_URL, post_payload, headers).catch(error => console.log(error.response));
  // console.log("Step 1 Complete!");


  // Step 3) make a PUT request to https://api.luan.tools/api/tasks/{task_id}
  // where task id is provided in the response from the request in Step 1.
  const task_id = response.data.id
  const task_url = BASE_URL + task_id
  // console.log("PUTting to " + task_url)
  const put_payload = {
    'input_spec': {
      'style': style_id,
      'prompt': prompt,
      'target_image_weight': 0.1,
      'width': weight,
      'height': weight
    }
  }
  // console.log(task_url);
  await axios.put(task_url, JSON.stringify(put_payload), headers).catch(error => console.log(error.response));
  // console.log("Step 3 Complete!")

  // Step 4) Keep polling for images until the generation completes
  while (true == true) {
    let get_response = await axios.get(task_url, headers).catch(error => console.log(error.response));
    let state = get_response.data.state;
    if (state == "generating") {
      console.log("generating");
    } else if (state == "failed") {
      console.log("failed!");
      return {
        error: true,
        message: "failed",
        status: "failed",
        url: null
      }
      break;
    } else if (state == "completed") {
      var final_url = get_response.data.result;
      console.log("url: ", final_url);
      return {
        error: false,
        message: "complete",
        status: "complete",
        url: final_url
      }
      //сохранить в виде файла
      // axios({
      //   method: "get",
      //   url: final_url,
      //   responseType: "stream"
      // }).then(function (response) {
      //   // console.log(response);
      //   response.data.pipe(fs.createWriteStream("img.jpg"));
      //   console.log("Generated image downloaded to img.jpg! enjoy :)")
      // });
      // break;
    }
    await new Promise(res => setTimeout(res, 4000));
  }
}

// console.log(await send_task_to_dream_api(13, "sadiasjdjioasdio"));